spring:
  datasource:
    url: jdbc:mysql://localhost:3306/assistance?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    root: info
    com:
      xjtu:
        xjtuse: debug
    web: trace

mybatis:
  mapper-locations: mapper/*.xml